import type { BreakingChange } from '../changelog/types.js';
import type { UsageMatch } from '../detector/scanUsage.js';

export interface PrDescriptionInput {
  change: BreakingChange;
  matches: UsageMatch[];
  branchName: string;
  diff: string;
}

export interface PrDescription {
  title: string;
  body: string;
}

/**
 * Drafts a PR title/body. Uses Claude when ANTHROPIC_API_KEY is set; otherwise
 * falls back to a deterministic template so the demo never depends on network access.
 */
export async function generatePrDescription(input: PrDescriptionInput): Promise<PrDescription> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (apiKey) {
    try {
      return await generateWithClaude(input, apiKey);
    } catch (err) {
      console.error(
        `Claude PR description generation failed, falling back to template: ${(err as Error).message}`,
      );
    }
  }
  return generateTemplate(input);
}

function affectedFiles(matches: UsageMatch[]): string[] {
  return [...new Set(matches.map((m) => m.filePath))];
}

function generateTemplate(input: PrDescriptionInput): PrDescription {
  const { change, matches, diff } = input;
  const title = `Migrate ${change.sdk}: ${change.detect.objectPath}.${change.detect.method} -> ${change.replacement.objectPath}.${change.replacement.method}`;
  const fileList = affectedFiles(matches)
    .map((f) => `- ${f}`)
    .join('\n');

  const body = `## Why

${change.title}

${change.migrationNote}

**Sunset date:** ${change.sunsetDate}
${change.changelogUrl ? `**Changelog:** ${change.changelogUrl}` : ''}

## Affected call sites

${fileList}

## Diff

\`\`\`diff
${diff}
\`\`\`

---
_Generated by DriftPilot (template fallback — set ANTHROPIC_API_KEY for an AI-authored description)._
`;

  return { title, body };
}

async function generateWithClaude(input: PrDescriptionInput, apiKey: string): Promise<PrDescription> {
  const { default: Anthropic } = await import('@anthropic-ai/sdk');
  const client = new Anthropic({ apiKey });
  const { change, matches, diff } = input;

  const prompt = `You are drafting a pull request that migrates code off a deprecated third-party API method before its sunset date.

Changelog entry (JSON):
${JSON.stringify(change, null, 2)}

Affected files:
${affectedFiles(matches).join('\n')}

Diff of the migration:
${diff}

Write a concise one-line PR title and a markdown PR body explaining the breaking change, why it matters, the sunset date, and what changed. Respond in exactly this format:
TITLE: <title>
BODY:
<body>`;

  const response = await client.messages.create({
    model: 'claude-sonnet-5',
    max_tokens: 1024,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content
    .map((block) => (block.type === 'text' ? block.text : ''))
    .join('\n');

  const titleMatch = text.match(/TITLE:\s*(.+)/);
  const bodyMatch = text.match(/BODY:\s*([\s\S]*)/);
  if (!titleMatch || !bodyMatch) {
    throw new Error('Unexpected response format from Claude');
  }

  return { title: titleMatch[1].trim(), body: bodyMatch[1].trim() };
}
